---
- name: Deploy Docker container
  hosts: all
  tasks:
    - name: Ensure Docker is installed
      community.docker.docker_container:
        state: present

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
        state: present

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ lookup('env', 'IMAGE_NAME') }}"
        force_source: pull
        source: pull

    - name: Restart container with new image
      community.docker.docker_container:
        name: nginx_container
        image: "{{ lookup('env', 'IMAGE_NAME') }}"
        state: started
        ports:
          - "80:80"
        recreate: true

