name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

env:
  IMAGE_NAME: kaniuxxjd/nginx-test-app:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t nginx-test-app .

    - name: Run Nginx container
      run: docker run -d -p 80:80 nginx-test-app

    - name: Test Nginx
      run: |
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt
        python3 check_nginx.py

    - name: Tag Docker image
      run: docker tag nginx-test-app:latest $IMAGE_NAME

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_IP_ADDRESS: ${{ secrets.VM_IP_ADDRESS }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$VM_IP_ADDRESS << 'EOF'
            docker pull $IMAGE_NAME
            docker stop nginx_container || true
            docker rm nginx_container || true
            docker run -d --name nginx_container -p 80:80 $IMAGE_NAME
EOF